"""Shared helpers: describe the commit, machine and compiler behind a result."""

from __future__ import annotations

import os
import platform
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def git_commit() -> str:
    try:
        sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, check=True,
                             capture_output=True, text=True).stdout.strip()
        dirty = subprocess.run(["git", "status", "--porcelain", "--untracked-files=no",
                                "--", "src", "include", "apps", "bench", "CMakeLists.txt"],
                               cwd=ROOT, check=True, capture_output=True, text=True).stdout.strip()
        return sha + ("-dirty" if dirty else "")
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def cpu_name() -> str:
    system = platform.system()
    try:
        if system == "Linux":
            for line in Path("/proc/cpuinfo").read_text().splitlines():
                if line.startswith("model name"):
                    return line.split(":", 1)[1].strip()
        elif system == "Darwin":
            return subprocess.run(["sysctl", "-n", "machdep.cpu.brand_string"],
                                  capture_output=True, text=True).stdout.strip()
        elif system == "Windows":
            import winreg  # noqa: PLC0415

            key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,
                                 r"HARDWARE\DESCRIPTION\System\CentralProcessor\0")
            return winreg.QueryValueEx(key, "ProcessorNameString")[0].strip()
    except OSError:
        pass
    return platform.processor() or "unknown CPU"


def compiler(build_dir: Path) -> str:
    for f in sorted(build_dir.glob("CMakeFiles/*/CMakeCXXCompiler.cmake")):
        text = f.read_text()
        cid = re.search(r'set\(CMAKE_CXX_COMPILER_ID "([^"]*)"\)', text)
        ver = re.search(r'set\(CMAKE_CXX_COMPILER_VERSION "([^"]*)"\)', text)
        if cid:
            return f"{cid.group(1)} {ver.group(1) if ver else ''}".strip()
    return "unknown compiler"


def build_type(build_dir: Path) -> str:
    cache = build_dir / "CMakeCache.txt"
    if cache.exists():
        m = re.search(r"^CMAKE_BUILD_TYPE:\w+=(.*)$", cache.read_text(), re.MULTILINE)
        if m:
            return m.group(1)
    return "unknown"


def header(script: str, build_dir: Path) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (f"<!-- Generated by {script}; do not edit by hand. -->\n\n"
            f"Commit `{git_commit()}` | {now} | {cpu_name()} ({os.cpu_count()} hardware threads) | "
            f"{platform.system()} {platform.release()} | {compiler(build_dir)}, "
            f"{build_type(build_dir)}\n\n")


def exe(build_dir: Path, sub: str, name: str) -> Path:
    for candidate in (build_dir / sub / name, build_dir / sub / f"{name}.exe"):
        if candidate.exists():
            return candidate
    raise FileNotFoundError(f"{name} not found under {build_dir / sub}; build the project first")
